export type MenuItem = {
  id: string;
  nameAr: string;
  nameHe?: string;
  nameEn?: string;
  descAr?: string;
  descHe?: string;
  descEn?: string;
  price: number;
  image?: string;
  tag?: 'new' | 'popular' | 'signature';
};

export type MenuCategory = {
  id: string;
  key: string;
  items: MenuItem[];
};

export const menuData: MenuCategory[] = [
  {
    id: 'breakfast',
    key: 'breakfast',
    items: [
      {
        id: 'bf-1',
        nameAr: 'فطور زوجي',
        nameHe: 'ארוחת בוקר לזוג',
        nameEn: 'Couple\'s Breakfast',
        descAr: '١٣ نوعاً من الممراحيم: بانكيك، حمص مع لحمة، لحمة بندورة، فوكاتشا مع سلطات، بلاطة أجبان، و٤ مشروبات',
        descHe: '13 סוגי ממרחים: פנקייק, חומוס עם בשר, בשר עגבניות, פוקצ\'ה עם סלטים, צלחת גבינות ו-4 שתיות',
        descEn: '13 types of spreads: pancakes, hummus with meat, meat with tomatoes, focaccia with salads, cheese plate, and 4 drinks',
        price: 150,
        tag: 'popular',
      },
      {
        id: 'bf-2',
        nameAr: 'فطور شخصي',
        nameHe: 'ארוחת בוקר אישית',
        nameEn: 'Personal Breakfast',
        descAr: 'حسب الاختيار: عجة، شكشوكة، بيض عيون، مخلوطة، ٧ أنواع ممراحيم، سلطة، بانكيك',
        descHe: 'לבחירה: חביתה, שקשוקה, ביצת עין, מעורבת, 7 סוגי ממרחים, סלט, פנקייק',
        descEn: 'Your choice: omelette, shakshuka, fried egg, mixed, 7 spreads, salad, pancake',
        price: 75,
      },
    ],
  },
  {
    id: 'mains',
    key: 'mains',
    items: [
      {
        id: 'm-1',
        nameAr: 'انتركوت',
        nameHe: 'אנטריקוט',
        nameEn: 'Entrecote',
        descAr: 'قطعة لحم مشوية على الفحم بأشهى التتبيلات والنكهات',
        descHe: 'נתח בקר על הגחלים עם תיבול מיוחד',
        descEn: 'Charcoal-grilled beef with signature marinade',
        price: 125,
        tag: 'signature',
      },
      {
        id: 'm-2',
        nameAr: 'فيليه',
        nameHe: 'פילה',
        nameEn: 'Fillet',
        descAr: 'فيليه لحم طري مشوي على الفحم',
        descHe: 'פילה בקר רך על הגחלים',
        descEn: 'Tender beef fillet grilled over charcoal',
        price: 120,
        tag: 'popular',
      },
      {
        id: 'm-3',
        nameAr: 'صدر الدجاج',
        nameHe: 'חזה עוף',
        nameEn: 'Chicken Breast',
        descAr: 'صدر دجاج مشوي بأشهى التتبيلات',
        descHe: 'חזה עוף על הגחלים',
        descEn: 'Grilled chicken breast with special marinade',
        price: 75,
      },
      {
        id: 'm-4',
        nameAr: 'كباب',
        nameHe: 'קבב',
        nameEn: 'Kebab',
        descAr: 'كباب لحم مشوي على الفحم مع مرافقات',
        descHe: 'קבב על הגחלים עם תוספות',
        descEn: 'Charcoal grilled kebab with sides',
        price: 75,
      },
      {
        id: 'm-5',
        nameAr: 'برجيت',
        nameHe: 'ברגר',
        nameEn: 'Burger',
        descAr: 'برجر لحم أنغوس محلي مشوي',
        descHe: 'המבורגר אנגוס על הגחלים',
        descEn: 'Grilled Angus beef burger',
        price: 80,
      },
      {
        id: 'm-6',
        nameAr: 'ستروغنوف (لحمة - جاج)',
        nameHe: 'סטרוגנוב (בשר/עוף)',
        nameEn: 'Stroganoff (Meat/Chicken)',
        descAr: 'ستروغنوف كريمي مع أرز بسمتي',
        descHe: 'סטרוגנוף קרמי עם אורז בסמטי',
        descEn: 'Creamy stroganoff with basmati rice',
        price: 75,
      },
    ],
  },
  {
    id: 'fish',
    key: 'fish',
    items: [
      {
        id: 'f-1',
        nameAr: 'سمك مشوي',
        nameHe: 'דג על הגחלים',
        nameEn: 'Grilled Fish',
        descAr: 'سمك طازج مشوي على الفحم مع لمون وأعشاب',
        descHe: 'דג טרי על הגחלים עם לימון ועשבי תיבול',
        descEn: 'Fresh grilled fish with lemon and herbs',
        price: 95,
        tag: 'popular',
      },
      {
        id: 'f-2',
        nameAr: 'سمك سيلان',
        nameHe: 'דג צ\'ילאן',
        nameEn: 'Ceylon Fish',
        descAr: 'سمك بصلصة سيلان الحارة اللذيذة',
        descHe: 'דג ברוטב צ\'ילאן חריף',
        descEn: 'Fish in spicy Ceylon sauce',
        price: 95,
      },
      {
        id: 'f-3',
        nameAr: 'جمبري',
        nameHe: "שרימפס",
        nameEn: 'Shrimp',
        descAr: 'جمبري مشوي مع ثوم وزيت زيتون',
        descHe: "שרימפס על הגחלים עם שום ושמן זית",
        descEn: 'Grilled shrimp with garlic and olive oil',
        price: 105,
        tag: 'signature',
      },
    ],
  },
  {
    id: 'appetizers',
    key: 'appetizers',
    items: [
      {
        id: 'a-1',
        nameAr: 'حمص',
        nameHe: 'חומוס',
        nameEn: 'Hummus',
        descAr: 'حمص طازج محلي الصنع',
        descHe: 'חומוס ביתי טרי',
        descEn: 'Fresh homemade hummus',
        price: 25,
      },
      {
        id: 'a-2',
        nameAr: 'حمص مع لحمة',
        nameHe: 'חומוס עם בשר',
        nameEn: 'Hummus with Meat',
        descAr: 'حمص طازج مع لحمة مفرومة وصنوبر',
        descHe: 'חומוס טרי עם בשר טחון וצנוברים',
        descEn: 'Fresh hummus with ground meat and pine nuts',
        price: 38,
        tag: 'popular',
      },
      {
        id: 'a-3',
        nameAr: 'متبل',
        nameHe: 'מטבל',
        nameEn: 'Mutabbal',
        descAr: 'متبل باذنجان مشوي طازج',
        descHe: 'מטבל חציל צלוי טרי',
        descEn: 'Fresh roasted eggplant mutabbal',
        price: 25,
      },
      {
        id: 'a-4',
        nameAr: 'فتوش',
        nameHe: 'פתוש',
        nameEn: 'Fattoush',
        descAr: 'سلطة فتوش طازجة مع خبز مقرمش',
        descHe: 'סלט פתוש טרי עם לחם קריספי',
        descEn: 'Fresh fattoush salad with crispy bread',
        price: 32,
      },
      {
        id: 'a-5',
        nameAr: 'كبة مقلية',
        nameHe: 'קובה מטוגנת',
        nameEn: 'Fried Kibbeh',
        descAr: 'كبة مقلية مقرمشة محشوة باللحم والصنوبر',
        descHe: 'קובה מטוגנת פריכה במילוי בשר וצנוברים',
        descEn: 'Crispy fried kibbeh stuffed with meat and pine nuts',
        price: 35,
        tag: 'popular',
      },
      {
        id: 'a-6',
        nameAr: 'فلافل',
        nameHe: 'פלאפל',
        nameEn: 'Falafel',
        descAr: 'فلافل مقرمشة طازجة',
        descHe: 'פלאפל פריך וטרי',
        descEn: 'Fresh crispy falafel',
        price: 22,
      },
    ],
  },
  {
    id: 'salads',
    key: 'salads',
    items: [
      {
        id: 's-1',
        nameAr: 'سلطة شيري مع مكسرات',
        nameHe: 'סלט שרי עם אגוזים',
        nameEn: 'Cherry Salad with Nuts',
        descAr: 'طماطم شيري مع مكسرات محمصة وصلصة بلسمية',
        descHe: 'עגבניות שרי עם אגוזים קלויים ורוטב בלסמי',
        descEn: 'Cherry tomatoes with roasted nuts and balsamic dressing',
        price: 38,
        tag: 'signature',
      },
      {
        id: 's-2',
        nameAr: 'سلطة خضراء',
        nameHe: 'סלט ירוק',
        nameEn: 'Green Salad',
        descAr: 'سلطة خضراء طازجة موسمية',
        descHe: 'סלט ירוק טרי ועונתי',
        descEn: 'Fresh seasonal green salad',
        price: 30,
      },
      {
        id: 's-3',
        nameAr: 'سلطة سيزر',
        nameHe: 'סלט קיסר',
        nameEn: 'Caesar Salad',
        descAr: 'سلطة سيزر كلاسيكية مع كروتون وجبنة بارميزان',
        descHe: 'סלט קיסר קלאסי עם קרוטונים וגבינת פרמזן',
        descEn: 'Classic Caesar salad with croutons and parmesan',
        price: 42,
      },
    ],
  },
  {
    id: 'light',
    key: 'light',
    items: [
      {
        id: 'l-1',
        nameAr: 'خبز بالثوم',
        nameHe: 'לחם שום',
        nameEn: 'Garlic Bread',
        descAr: 'خبز طازج محمص بالثوم والزيت',
        descHe: 'לחם טרי קלוי עם שום ושמן',
        descEn: 'Fresh toasted bread with garlic and oil',
        price: 18,
      },
      {
        id: 'l-2',
        nameAr: 'فوكاتشا',
        nameHe: "פוקצ'ה",
        nameEn: 'Focaccia',
        descAr: 'فوكاتشا طازجة مع زيت زيتون وأعشاب',
        descHe: "פוקצ'ה טרייה עם שמן זית ועשבי תיבול",
        descEn: 'Fresh focaccia with olive oil and herbs',
        price: 22,
        tag: 'popular',
      },
      {
        id: 'l-3',
        nameAr: 'بروسكيتا',
        nameHe: 'ברוסקטה',
        nameEn: 'Bruschetta',
        descAr: 'بروسكيتا مقرمشة مع طماطم وريحان',
        descHe: 'ברוסקטה פריכה עם עגבניות ובזיל',
        descEn: 'Crispy bruschetta with tomatoes and basil',
        price: 28,
      },
    ],
  },
  {
    id: 'italian',
    key: 'italian',
    items: [
      {
        id: 'it-1',
        nameAr: 'باستا أرابياتا',
        nameHe: 'פסטה ארביאטה',
        nameEn: 'Pasta Arrabiata',
        descAr: 'باستا بصلصة طماطم حارة',
        descHe: 'פסטה ברוטב עגבניות חריף',
        descEn: 'Pasta in spicy tomato sauce',
        price: 58,
      },
      {
        id: 'it-2',
        nameAr: 'باستا كريمة الفطر',
        nameHe: 'פסטה שמנת פטריות',
        nameEn: 'Mushroom Cream Pasta',
        descAr: 'باستا بصلصة كريمة الفطر الإيطالية',
        descHe: 'פסטה ברוטב שמנת פטריות איטלקי',
        descEn: 'Pasta in Italian mushroom cream sauce',
        price: 65,
        tag: 'popular',
      },
      {
        id: 'it-3',
        nameAr: 'ريزوتو الفطر',
        nameHe: 'ריזוטו פטריות',
        nameEn: 'Mushroom Risotto',
        descAr: 'ريزوتو كريمي بالفطر الطازج',
        descHe: 'ריזוטו קרמי עם פטריות טריות',
        descEn: 'Creamy risotto with fresh mushrooms',
        price: 68,
        tag: 'signature',
      },
      {
        id: 'it-4',
        nameAr: 'بيتزا مرغريتا',
        nameHe: 'פיצה מרגריטה',
        nameEn: 'Pizza Margherita',
        descAr: 'بيتزا مرغريتا كلاسيكية بالجبنة الطازجة',
        descHe: 'פיצה מרגריטה קלאסית עם גבינה טרייה',
        descEn: 'Classic margherita pizza with fresh mozzarella',
        price: 58,
      },
    ],
  },
  {
    id: 'extras',
    key: 'extras',
    items: [
      {
        id: 'ex-1',
        nameAr: 'أرز بسمتي',
        nameHe: 'אורז בסמטי',
        nameEn: 'Basmati Rice',
        price: 15,
      },
      {
        id: 'ex-2',
        nameAr: 'خبز طازج',
        nameHe: 'לחם טרי',
        nameEn: 'Fresh Bread',
        price: 10,
      },
      {
        id: 'ex-3',
        nameAr: 'صلصة تحينة',
        nameHe: 'רוטב טחינה',
        nameEn: 'Tahini Sauce',
        price: 10,
      },
      {
        id: 'ex-4',
        nameAr: 'خضروات مشوية',
        nameHe: 'ירקות על הגחלים',
        nameEn: 'Grilled Vegetables',
        price: 22,
      },
    ],
  },
  {
    id: 'drinks',
    key: 'drinks',
    items: [
      {
        id: 'd-1',
        nameAr: 'موخيتو',
        nameHe: 'מוחיטו',
        nameEn: 'Mojito',
        descAr: 'موخيتو منعش بالنعناع والليمون',
        descHe: 'מוחיטו מרענן עם נענע ולימון',
        descEn: 'Refreshing mojito with mint and lime',
        price: 22,
        tag: 'popular',
      },
      {
        id: 'd-2',
        nameAr: 'ليموناضة',
        nameHe: 'לימונדה',
        nameEn: 'Lemonade',
        price: 18,
      },
      {
        id: 'd-3',
        nameAr: 'مشروبات غازية',
        nameHe: 'שתייה מוגזת',
        nameEn: 'Soft Drinks',
        price: 12,
      },
      {
        id: 'd-4',
        nameAr: 'قهوة عربية',
        nameHe: 'קפה ערבי',
        nameEn: 'Arabic Coffee',
        price: 8,
      },
    ],
  },
  {
    id: 'juices',
    key: 'juices',
    items: [
      {
        id: 'j-1',
        nameAr: 'عصير برتقال طازج',
        nameHe: 'מיץ תפוזים סחוט טרי',
        nameEn: 'Fresh Orange Juice',
        price: 18,
        tag: 'popular',
      },
      {
        id: 'j-2',
        nameAr: 'سموذي فواكه',
        nameHe: 'שייק פירות',
        nameEn: 'Fruit Smoothie',
        price: 22,
      },
      {
        id: 'j-3',
        nameAr: 'شيك شوكولاتة',
        nameHe: 'שייק שוקולד',
        nameEn: 'Chocolate Shake',
        price: 24,
        tag: 'popular',
      },
    ],
  },
  {
    id: 'special_drinks',
    key: 'special_drinks',
    items: [
      {
        id: 'sd-1',
        nameAr: 'موخيتو الفراولة',
        nameHe: 'מוחיטו תות',
        nameEn: 'Strawberry Mojito',
        price: 28,
        tag: 'signature',
      },
      {
        id: 'sd-2',
        nameAr: 'ليموناضة النعناع',
        nameHe: 'לימונדה נענע',
        nameEn: 'Mint Lemonade',
        price: 22,
      },
      {
        id: 'sd-3',
        nameAr: 'باشن فروت',
        nameHe: 'פסיפלורה',
        nameEn: 'Passion Fruit',
        price: 26,
      },
    ],
  },
  {
    id: 'desserts',
    key: 'desserts',
    items: [
      {
        id: 'des-1',
        nameAr: 'كنافة',
        nameHe: 'כנאפה',
        nameEn: 'Kunafa',
        descAr: 'كنافة عربية طازجة بالقطر والقشطة',
        descHe: 'כנאפה ערבית טרייה עם סירופ וקרם',
        descEn: 'Fresh Arabic kunafa with syrup and cream',
        price: 28,
        tag: 'popular',
      },
      {
        id: 'des-2',
        nameAr: 'تشيزكيك',
        nameHe: 'צ\'יזקייק',
        nameEn: 'Cheesecake',
        descAr: 'تشيزكيك كريمي مع توت',
        descHe: "צ'יזקייק קרמי עם פירות יער",
        descEn: 'Creamy cheesecake with berries',
        price: 32,
      },
      {
        id: 'des-3',
        nameAr: 'بانا كوتا',
        nameHe: 'פנה קוטה',
        nameEn: 'Panna Cotta',
        descAr: 'بانا كوتا إيطالية مع صلصة الكراميل',
        descHe: 'פנה קוטה איטלקית עם רוטב קרמל',
        descEn: 'Italian panna cotta with caramel sauce',
        price: 30,
        tag: 'signature',
      },
    ],
  },
  {
    id: 'hookah',
    key: 'hookah',
    items: [
      {
        id: 'h-1',
        nameAr: 'أرجيلة فاخرة',
        nameHe: 'נרגילה מפוארת',
        nameEn: 'Premium Hookah',
        descAr: 'أرجيلة بمختلف النكهات المميزة',
        descHe: 'נרגילה במגוון טעמים מיוחדים',
        descEn: 'Hookah with a variety of premium flavors',
        price: 60,
      },
      {
        id: 'h-2',
        nameAr: 'أرجيلة توت',
        nameHe: 'נרגילה תות',
        nameEn: 'Strawberry Hookah',
        price: 55,
        tag: 'popular',
      },
      {
        id: 'h-3',
        nameAr: 'أرجيلة بطيخ',
        nameHe: 'נרגילה אבטיח',
        nameEn: 'Watermelon Hookah',
        price: 55,
      },
    ],
  },
];
